spring:
  application.name: payshield
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payshield}
    username: ${SPRING_DATASOURCE_USERNAME:payshield}
    password: ${SPRING_DATASOURCE_PASSWORD:payshield}
  jpa:
    open-in-view: false
    hibernate.ddl-auto: validate
  flyway.enabled: true
management.endpoints.web.exposure.include: health,info
