package com.payshield.service;
import com.payshield.api.*; import com.payshield.domain.*; import com.payshield.repo.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.util.*;
@Service public class PaymentService {
 private final PaymentRepository payments; private final IdempotencyRepository keys; private final PaymentTransitionRepository transitions; private final LedgerRepository ledger; private final OutboxRepository outbox; private final MockGateway gateway;
 public PaymentService(PaymentRepository p,IdempotencyRepository k,PaymentTransitionRepository t,LedgerRepository l,OutboxRepository o,MockGateway g){payments=p;keys=k;transitions=t;ledger=l;outbox=o;gateway=g;}
 @Transactional public PaymentResponse create(PaymentRequest req,String key){requireKey(key);String hash=hash("PAYMENT:"+req); Optional<IdempotencyRecord> existing=keys.lockByKey(key);if(existing.isPresent()) return existingResponse(existing.get(),hash); IdempotencyRecord record=new IdempotencyRecord(key,hash,"PAYMENT"); try{keys.saveAndFlush(record);}catch(DataIntegrityViolationException e){throw new PaymentException(409,"Request with this idempotency key is already processing; retry shortly");} Payment p=new Payment(UUID.randomUUID(),req.amount(),req.currency(),req.merchantReference(),req.customerId(),req.paymentToken()); payments.save(p); transition(p,PaymentStatus.CREATED,PaymentStatus.PROCESSING); MockGateway.GatewayResult result=gateway.charge(req.paymentToken()); if(result.succeeded()){transition(p,PaymentStatus.PROCESSING,PaymentStatus.SUCCEEDED);writeLedger(p,false);event(p,"payment.succeeded");}else {p.fail(result.reason());transitions.save(new PaymentTransition(p.getId(),PaymentStatus.PROCESSING,PaymentStatus.FAILED));event(p,"payment.failed");} record.setResourceId(p.getId()); return PaymentResponse.from(p); }
 @Transactional(readOnly=true) public PaymentResponse get(UUID id){return PaymentResponse.from(find(id));}
 @Transactional public PaymentResponse refund(UUID id,String key){requireKey(key);Payment p=find(id);String hash=hash("REFUND:"+id);Optional<IdempotencyRecord> existing=keys.lockByKey(key);if(existing.isPresent())return existingResponse(existing.get(),hash);if(p.getStatus()!=PaymentStatus.SUCCEEDED)throw new PaymentException(409,"Only a successful payment can be refunded");IdempotencyRecord r=new IdempotencyRecord(key,hash,"REFUND");r.setResourceId(id);try{keys.saveAndFlush(r);}catch(DataIntegrityViolationException e){throw new PaymentException(409,"Refund with this idempotency key is already processing; retry shortly");}transition(p,PaymentStatus.SUCCEEDED,PaymentStatus.REFUNDED);writeLedger(p,true);event(p,"payment.refunded");return PaymentResponse.from(p);}
 @Transactional(readOnly=true) public List<LedgerResponse> ledger(UUID id){find(id);return ledger.findByPaymentIdOrderByCreatedAt(id).stream().map(LedgerResponse::from).toList();}
 private PaymentResponse existingResponse(IdempotencyRecord r,String hash){if(!r.getRequestHash().equals(hash))throw new PaymentException(409,"Idempotency key was reused with a different request");if(r.getResourceId()==null)throw new PaymentException(409,"Request is currently processing; retry shortly");return get(r.getResourceId());} private Payment find(UUID id){return payments.findById(id).orElseThrow(()->new PaymentException(404,"Payment not found"));} private void transition(Payment p,PaymentStatus from,PaymentStatus to){p.status(to);transitions.save(new PaymentTransition(p.getId(),from,to));} private void writeLedger(Payment p,boolean refund){String a=refund?"merchant_payable":"customer_clearing",b=refund?"customer_clearing":"merchant_payable";ledger.save(new LedgerEntry(p.getId(),"DEBIT",a,p.getAmount(),p.getCurrency()));ledger.save(new LedgerEntry(p.getId(),"CREDIT",b,p.getAmount(),p.getCurrency()));} private void event(Payment p,String type){outbox.save(new OutboxEvent(p.getId(),type,"{\"paymentId\":\""+p.getId()+"\",\"status\":\""+p.getStatus()+"\"}"));} private void requireKey(String key){if(key==null||key.isBlank())throw new PaymentException(400,"Idempotency-Key header is required");} private String hash(String value){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
